### ISSUE TITLE
Building TASM - nvUtils.h

### ISSUE THREAD

**Issue by faromero** [maureendaum/TASM-LightDB#1]
Hello,
I am interested in trying out your prototype of TASM;  I am getting tripped up on the build not finding _nvUtils.h_ in _tasm/encoding/include/EncodeAPI.h._ Is this header from an NVIDIA library that needs to be installed, or is this a part of your source code that I am missing/am not pointing to properly?

Thanks for your help in advance!

**Comment by maureendaum** [comment]
Thanks for your interest in the project! I apologize that it isn't in a very user-friendly state at the moment, I'm going to put some time into that this week.

It looks like that import is an old external resource that isn't part of more recent NVIDIA distributions, so I removed it. Let me know if you still have trouble building.

Just as a heads up, I introduced some performance bugs when I extracted TASM from LightDB that I haven't resolved yet. If you are interested in using the C++ interface through LightDB, let me know and I'll put together some documentation for how to do that!

**Comment by faromero** [comment]
Great, thank you so much for your help! No worries at all about the documentation, I can work with what you have here.

One more question about the build: the compiler complains about [these lines](https://github.com/maureendaum/TASM/blob/6e525f34321909fecf6d028d23e6b9cc3b0184ff/tasm/encoding/include/MP4Reader.h#L98-L100), saying it can't convert _flags_ to type _GF_ISONaluExtractMode_. I am not familiar with the _gpac_ library, but it seems it is because the resulting bit-wise oring is not a "valid enum" value based on the [source code](https://github.com/gpac/gpac/blob/35c4644cb57cfcf6c67ab986679fa69fb9072ec8/include/gpac/isomedia.h#L3226-L3241) for _GF_ISONaluExtractMode_. Based on this, is it sufficient to just pass the _GF_ISOM_NALU_EXTRACT_ANNEXB_FLAG_ flag since if I am understanding it correctly, it will also apply the _GF_ISOM_NALU_EXTRACT_INBAND_PS_FLAG_ flag? Passing just the _GF_ISOM_NALU_EXTRACT_ANNEXB_FLAG_ flag gets me through the whole build, and I will test some runs next.

Thanks again for all your help with this!

**Comment by maureendaum** [comment]
Yes, I think that should be fine! I'll fix that in a new commit.

**Comment by maureendaum** [comment]
Actually, now that I've tried it on my end, I'm not sure whether that will work. We may have different gpac versions because I don't get that error, and when I drop `GF_ISOM_NALU_EXTRACT_INBAND_PS_FLAG`, the decoder fails to decode any of the frames for `select`. 

If, when you try to do a selection, you see a line printed like `Num-frames-from-decoder: 0`, then removing that flag may have broken it.  I created a new issue to track this inconsistency: #3

**Comment by maureendaum** [comment]
#3

**Comment by faromero** [comment]
Makes sense! I apologize for my lack of familiarity with _gpac_, but if this helps, here is the version I see when I run the binary associated with the _gpac_ build:
`gpac - GPAC command line filter engine - version 1.1.0-DEV-rev468-g0dc842d37-master`

To run, I was using your example, and it seems that I can import tasm correctly, but it doesn't find the TASM() attribute. I assume this is because some installation of packages escaped me (after _make_, I did run _make install_, but perhaps I missed something python-specific). (I can also move this to a different thread if you prefer.)

**Comment by maureendaum** [comment]
I'm not 100% sure which gpac version I'm using, but it's definitely older than that. MP4Box is using all the way back from GPAC version 0.5.2-DEV-revVersion. I should probably update to at least 1.0.0.

For the issue importing tasm, I don't think I'm adding the library to the python path. Does it work if you try to run from `<build>/python/`?

**Comment by faromero** [comment]
Regarding _gpac_: no problem, if this doesn't work out, I can downgrade to something around the version you specified.
Regarding python: I realized I was running this in python3, not python2, and you are correct that I should be running in `build/python`. I get a symbols error now associated with the TileConfiguration protobuf, but at least means it's trying to correctly access the shared object for the attributes: `tasm/_tasm.so: undefined symbol: _ZN7lightdb13serialization17TileConfigurationC1Ev`. Likely a protobuf version issue which I am investigating; what version are you using?

**Comment by maureendaum** [comment]
That's progress! I'm using Protobuf version: 2.6.1

**Comment by maureendaum** [comment]
If you are interested, I put together a Docker file to make it easier to get the right dependencies installed (and I upgraded to python3). It's currently available on the `docker` branch, and I updated the README with instructions for building it locally while I figure out how to get it on DockerHub.

**Comment by faromero** [comment]
I am **very** interested, thanks for putting that together! I will give it a go.
