### ISSUE TITLE
How to use Homomorphic Stitching?

### ISSUE THREAD

**Issue by InkosiZhong** [maureendaum/TASM-LightDB#9]
Thanks a lot for your great work.
I wonder if there is an example for homomorphic stitching？

**Comment by InkosiZhong** [comment]
Is there any script or command that can recovery the NxM tiles into ONE .mp4 file to replay?

**Comment by maureendaum** [comment]
There currently isn't a function to output a .mp4 file, but cells 12 and 14 in the [example notebook](https://github.com/uwdb/TASM/blob/docker/python/Examples/Basics.ipynb) perform homomorphic stitching to produce full frames from tiles.
`select_frames` performs homomorphic stitching to produce an encoded video byte stream. Currently this gets piped to a video decoder, but I think if it instead were piped to a .mp4 file it would do what you are asking for.

**Comment by InkosiZhong** [comment]
I got it, thank you so much
